### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by MHIGists** [SalmonGER/StatsPE#43] opened 2017-02-19 22:54 UTC
Version 2.4.11
Server Software: Genisys
Data provider Mysql
Issue:
Mysql data provider is not working properly whenever I try to /stats playerName it says to check my spelling

**Comment by inxomnyaa** [comment] 2017-02-20 07:12
https://github.com/SalmonDE/StatsPE/blob/master/src/SalmonDE/StatsPE/StatsPE.php#L160
Its PlayerName.

**Comment by MHIGists** [comment] 2017-02-20 07:36
That's an example of any players name. Let's  say my nickname is foobar whenever I try to `/stats foobar` there is an error telling me to check my spelling

**Comment by inxomnyaa** [comment] 2017-02-20 07:42
https://github.com/SalmonDE/StatsPE/blob/master/src/SalmonDE/StatsPE/StatsPE.php#L280
Isn't it /stats list <name> for showing the stats of a specific player?

**Comment by Aericio** [comment] 2017-02-21 05:01
@thebigsmileXD `/stats list` would look for the user `list` and it isn't case sensitive.

**Comment by Aericio** [comment] 2017-02-21 05:06
@TheClimbing Can't reproduce, updated to the latest version. (using MySQL)

**Comment by SalmonDE** [comment] 2017-02-21 18:08
I'm planning to rewrite StatsPE soon (I hope). The code which was written by me in this project is really unclean and therefor doesn't surprise me to be buggy.
Thanks for you report! You reminded me about this project. :)

**Comment by MHIGists** [comment] 2017-02-21 21:04
Trying to do either /stats TheClimbing and /stats theclimbing didn't helped.Still saying to check my spelling dunno what is going on. I'm on the latest version of StatsPE

**Comment by Aericio** [comment] 2017-02-22 02:45
Check logs if statspe connected to mysql.. if it did connect, switch to json and see if its still a problem.

**Comment by SalmonDE** [comment] 2017-02-25 12:38
In the rewrite branch I'll first complete the json data provider and after that the mysql one. I'm sorry but it will take some time.

**Comment by SalmonDE** [comment] 2017-03-27 21:48
Nearly a month later I just wanted to tell you that I started working on the mysql provider @TheClimbing . I'm sorry for the big waiting time.

**Comment by SalmonDE** [comment] 2017-03-28 19:02
@TheClimbing I finished the MySQL provider, could you test it and tell me if your issue still occurs? Until then, I'll already close the issue, thanks for reporting! :)

**Closed as completed by SalmonDE** 2017-03-28 19:02 UTC
Labels: bug, enhancement
